//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECHSHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int ID_PRODUCT { get; set; }
        public string NAMEP { get; set; }
        public string PRICEP { get; set; }
        public string COUNTP { get; set; }
        public double GRADEP { get; set; }
        public string GROUPPROD { get; set; }
        public string DESCRYPTPROD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
